// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "counter.h"

Fl_Double_Window *counter_win=(Fl_Double_Window *)0;

Fl_Return_Button *increment_btn=(Fl_Return_Button *)0;

Fl_Button *decrement_btn=(Fl_Button *)0;

Fl_Output *output_text=(Fl_Output *)0;

/**
 Create main window
*/
Fl_Double_Window* make_window() {
  { counter_win = new Fl_Double_Window(375, 355, "Counter");
    { increment_btn = new Fl_Return_Button(105, 30, 155, 80, "Increment");
      increment_btn->tooltip("Increment the counter by 1.");
    } // Fl_Return_Button* increment_btn
    { decrement_btn = new Fl_Button(105, 240, 155, 90, "Decrement");
      decrement_btn->tooltip("Decrement the counter by 1.");
    } // Fl_Button* decrement_btn
    { output_text = new Fl_Output(105, 160, 155, 25);
      output_text->tooltip("Counter value");
      output_text->labeltype(FL_NO_LABEL);
      Fl_Group::current()->resizable(output_text);
    } // Fl_Output* output_text
    counter_win->end();
  } // Fl_Double_Window* counter_win
  return counter_win;
}
