// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef counter_h
#define counter_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *counter_win;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *increment_btn;
#include <FL/Fl_Button.H>
extern Fl_Button *decrement_btn;
#include <FL/Fl_Output.H>
extern Fl_Output *output_text;
Fl_Double_Window* make_window();
#endif
